# Textual Embeddings Adventure Starts Here

Our first goal should be to understand whether generic sentence embeddings can recover sensible connections between the candidate-test statements/questions and parliamentary business.

Conceptually, what we are doing is a semantic retrieval problem:

Candidate-test question → search through parliamentary votes → retrieve the most semantically related votes.

https://www.sbert.net/examples/sentence_transformer/applications/semantic-search/README.html

In [53]:
from pathlib import Path
import pandas as pd

DATA_DIR = Path("../data/temp_data")

roll_calls_file = DATA_DIR / "parliament" / "roll_calls_resume.csv"
candidate_test_file = DATA_DIR / "candidate_test" / "Kandidattestdata.xlsx"

df_roll_calls = pd.read_csv(roll_calls_file)
df_FV11 = pd.read_excel(candidate_test_file, sheet_name="FV11")
df_FV15 = pd.read_excel(candidate_test_file, sheet_name="FV15")
df_FV19 = pd.read_excel(candidate_test_file, sheet_name="FV19")
df_FV22 = pd.read_excel(candidate_test_file, sheet_name="FV22")

print(df_roll_calls.shape)
print(df_roll_calls.columns.tolist())
print(df_FV11.shape)
print(df_FV11.columns.tolist())

(2128, 12)
['afstemningid', 'sagstrinid', 'kommentar', 'afstemningstypeid', 'dato', 'sagstrintypeid', 'sagid', 'sagstypeid', 'sag_nummer', 'sag_titel', 'sag_titelkort', 'sag_resume']
(14540, 12)
['id', 'Firstname', 'Lastname', 'Candidates.Party', 'Storkreds', 'gender', 'birthdate', 'Question', 'Answer', 'Answer (Text)', 'IsImportant', 'Comment']

In [54]:
df_FV22.columns.tolist()

['id',
 'Candidates.Firstname',
 'Candidates.Lastname',
 'Candidates.Party',
 'Candidates.Area',
 'gender',
 'birthdate',
 'Question',
 'Answer',
 'Answer (text)',
 'IsImportant',
 'Comment']

In [55]:
# We don't need duplicate questions, so we can drop them and reset the index
df_questions_FV22 = (
    df_FV22[["Question"]]
    .drop_duplicates()
    .dropna()
    .reset_index(drop=True)
)

print(df_questions_FV22.shape)

df_questions_FV22.head(20)

(51, 1)

                                             Question
0   Afgiften på såkaldte hybridbiler bør være den ...
1   Aldersgrænsen for at købe øl og vin skal hæves...
2   Asylansøgere bør sendes til et land uden for E...
3   Behandling hos tandlægen bør være gratis for b...
4   Brugen af ukrudtsmidlet Roundup bør forbydes i...
5         Danmark bør indføre CO2-afgift på flyrejser
6         Danmark bør tage imod flere kvoteflygtninge
7   Danmark skal bruge flere penge på at styrke to...
8   Danmark skal undersøge muligheden for at udvik...
9            Den såkaldte Arne-pension skal afskaffes
10         Der bør dannes en regering hen over midten
11  Der bør åbnes for mere udenlandsk arbejdskraft...
12  Der skal afsættes penge til at hjælpe kontanth...
13  Der skal indføres en særlig skat på de allerhø...
14  Der skal indføres kvoter, der sikrer mindst 30...
15  Der skal indføres skat på fortjenesten ved sal...
16  Der skal udflyttes flere uddannelsespladser fr...
17  Der skal være permanent grænsekontrol mellem D...
18  Det er en god idé med naturnationalparker, hvo...
19  Det er en god idé, at dagpengesatsen for nyudd...

In [56]:
df_questions_FV22["election"] = "FV22"

In [57]:
def get_unique_questions(df, election):
    out = (
        df[["Question"]]
        .drop_duplicates()
        .dropna()
        .reset_index(drop=True)
    )
    
    out["election"] = election
    return out


df_questions_FV11 = get_unique_questions(df_FV11, "FV11")
df_questions_FV15 = get_unique_questions(df_FV15, "FV15")
df_questions_FV19 = get_unique_questions(df_FV19, "FV19")
df_questions_FV22 = get_unique_questions(df_FV22, "FV22")

In [58]:
# Unique questions per election
print("FV11:", len(df_questions_FV11))
print("FV15:", len(df_questions_FV15))
print("FV19:", len(df_questions_FV19))
print("FV22:", len(df_questions_FV22))

FV11: 20
FV15: 20
FV19: 45
FV22: 51

In [59]:
df_questions = pd.concat(
    [
        df_questions_FV11,
        df_questions_FV15,
        df_questions_FV19,
        df_questions_FV22,
    ],
    ignore_index=True,
)

print(df_questions.shape)
df_questions.head()

(136, 2)

                                            Question election
0         Den danske krone skal erstattes med euroen     FV11
1  EU skal fortsætte forhandlingerne med Tyrkiet ...     FV11
2                       Kirke og stat skal adskilles     FV11
3  Christiansborg favoriserer hovedstadsområdet p...     FV11
4  Folketinget skal fastsætte kvoter, så der alti...     FV11

In [60]:
df_questions["Question"].duplicated().sum()

np.int64(6)

In [61]:
df_questions[
    df_questions["Question"].duplicated(keep=False)
].sort_values("Question")

                                              Question election
22               Afgiften på cigaretter skal sættes op     FV15
40               Afgiften på cigaretter skal sættes op     FV19
33             Den offentlige kulturstøtte skal sænkes     FV15
75             Den offentlige kulturstøtte skal sænkes     FV19
2                         Kirke og stat skal adskilles     FV11
27                        Kirke og stat skal adskilles     FV15
82                        Kirke og stat skal adskilles     FV19
69   Kriminalitet begået i udsatte boligområder ska...     FV19
112  Kriminalitet begået i udsatte boligområder ska...     FV22
7    Offentlige institutioner i Danmark tager for m...     FV11
28   Offentlige institutioner i Danmark tager for m...     FV15

In [62]:
df_cases = (
    df_roll_calls[
        [
            "sagid",
            "sag_nummer",
            "sag_titel",
            "sag_titelkort",
            "sag_resume",
            "dato",
        ]
    ]
    .drop_duplicates(subset="sagid")
    .reset_index(drop=True)
)

In [63]:
df_cases["text"] = (
    df_cases["sag_titel"].fillna("")
    + " "
    + df_cases["sag_resume"].fillna("")
)

In [64]:
pd.set_option("display.max_colwidth", None)

df_cases[
    [
        "sag_nummer",
        "sag_titel",
        "sag_resume",
        "text"
    ]
].head(10)

,sag_nummer,sag_titel,sag_resume,text
0,L 200,Forslag til lov om ændring af virksomhedsskatteloven og kildeskatteloven. (Indgreb mod utilsigtet udnyttelse af virksomhedsordningen ved indskud af privat gæld m.v.).,"Loven ændrer virksomhedsskatteordningens regler, så det sikres, at selvstændigt erhvervsdrivende ikke kan udnytte virksomhedsskatteordningen utilsigtet. Med loven sikres det, at selvstændige ikke kan anvende lavt beskattede midler til at finansiere privatforbrug og afdrage på privat gæld, uden at midlerne beskattes som personlig indkomst. Der ændres ikke på virksomhedsskatteordningens grundlæggende struktur og indhold.\n\nLoven indeholder følgende elementer:\n- Selvstændige kan fremover kun spare op i virksomhedsordningen, hvis indskudskontoen er nul eller positiv. \n- Hvis aktiver, der indgår i virksomhedsordningen, fremover stilles til sikkerhed for gæld, der ikke indgår i virksomhedsordningen, anses et tilsvarende beløb for hævet af den selvstændige.\n- Rentekorrektionen forhøjes effektivt med 3 procentpoint med henblik på at eliminere den skattemæssige besparelse, som selvstændige kan opnå ved at placere private renteudgifter i virksomhedsordningen.\n- For selvstændige, der ved lovforslagets fremsættelse anvender virksomhedsordningen, og som allerede har stillet virksomhedens aktiver til sikkerhed for gæld, der ikke indgår i ordningen, eller har en negativ indskudskonto, suspenderes muligheden for at spare op i ordningen. Det gælder dog kun, hvis summen af den nominelle værdi af den negative indskudskonto og en evt. sikkerhedsstillelse overstiger 100.000 kr.\n\nBegrænsningerne i forhold til opsparingsmuligheden og forhøjelsen af rentekorrektionssatsen skønnes at indebære et umiddelbart merprovenu på ca. 0,8 mia. kr. i 2014, ca. 0,9 mia.kr. i 2015 og ca. 0,8 mia. kr. fra og med 2016. Den varige umiddelbare provenuvirkning skønnes at udgøre ca. 0,65 mia. kr. og ca. 0,5 mia. kr. efter tilbageløb.\n\nFor hurtigst muligt at give selvstændige klarhed om de nye regler, og da dele af loven skulle have virkning allerede fra og med fremsættelsen af lovforslaget af hensyn til indgrebets effektivitet og hindring af hamstring, er loven blevet vedtaget i indeværende folketingsår.","Forslag til lov om ændring af virksomhedsskatteloven og kildeskatteloven. (Indgreb mod utilsigtet udnyttelse af virksomhedsordningen ved indskud af privat gæld m.v.). Loven ændrer virksomhedsskatteordningens regler, så det sikres, at selvstændigt erhvervsdrivende ikke kan udnytte virksomhedsskatteordningen utilsigtet. Med loven sikres det, at selvstændige ikke kan anvende lavt beskattede midler til at finansiere privatforbrug og afdrage på privat gæld, uden at midlerne beskattes som personlig indkomst. Der ændres ikke på virksomhedsskatteordningens grundlæggende struktur og indhold.\n\nLoven indeholder følgende elementer:\n- Selvstændige kan fremover kun spare op i virksomhedsordningen, hvis indskudskontoen er nul eller positiv. \n- Hvis aktiver, der indgår i virksomhedsordningen, fremover stilles til sikkerhed for gæld, der ikke indgår i virksomhedsordningen, anses et tilsvarende beløb for hævet af den selvstændige.\n- Rentekorrektionen forhøjes effektivt med 3 procentpoint med henblik på at eliminere den skattemæssige besparelse, som selvstændige kan opnå ved at placere private renteudgifter i virksomhedsordningen.\n- For selvstændige, der ved lovforslagets fremsættelse anvender virksomhedsordningen, og som allerede har stillet virksomhedens aktiver til sikkerhed for gæld, der ikke indgår i ordningen, eller har en negativ indskudskonto, suspenderes muligheden for at spare op i ordningen. Det gælder dog kun, hvis summen af den nominelle værdi af den negative indskudskonto og en evt. sikkerhedsstillelse overstiger 100.000 kr.\n\nBegrænsningerne i forhold til opsparingsmuligheden og forhøjelsen af rentekorrektionssatsen skønnes at indebære et umiddelbart merprovenu på ca. 0,8 mia. kr. i 2014, ca. 0,9 mia.kr. i 2015 og ca. 0,8 mia. kr. fra og med 2016. Den varige umiddelbare provenuvirkning skønnes at udgøre ca. 0,65 mia. kr. og ca. 0,5 mia. kr. efter tilbageløb.\n\nFor hurtigst muligt at give selvstændige klarhed om de nye regler, og da dele af loven skulle have virkning allerede fra og med fremsættelsen af lovforslaget af hensyn til indgrebets effektivitet og hindring af hamstring, er loven blevet vedtaget i indeværende folketingsår."
1,L 4,"Forslag til lov om ændring af lov om afgift af elektricitet, lov om afgift af stenkul, brunkul og koks m.v., personskatteloven og forskellige andre love. (Tilbagerulning af forsyningssikkerhedsafgiften, nedsættelse af elvarmeafgiften, forhøjelse af elafgiften, tilpasning af afgiftsregler for VE-brændsler, forhøjelse af bundskatten og det skrå skatteloft, nedsættelse af den grønne check og afgiftsforhøjelse på cigarillos m.v.).","Lovforslaget betyder, at afgiftsforhøjelserne på fossile brændsler og den nye afgift på VE-brændsler, der følger af forsyningssikkerhedsafgiften, afskaffes fra den 1. januar 2015. Derudover nedsættes energiafgifterne på fossile brændsler (olie, kul og gas) med 7,9 kr./GJ, og elvarmeafgiften nedsættes parallelt. Desuden justeres afgifterne vedrørende bioolier m.v. Samlet skønnes tilbagerulningen af forsyningssikkerhedsafgiften m.v. at indebære et mindreprovenu efter indregning af tilbageløb og adfærdsændringer på ca. 3,0 mia. kr. (2014-niveau) i 2020. Tilbagerulningen finansieres ved en forhøjelse af bundskattesatsen og det skrå skatteloft med 0,28 procentpoint og en reduktion af den grønne check med 425 kr. i 2020 (fra 1.300 kr. til 875 kr.), når tilbagerulningen er fuldt indfaset. \n\nDer gennemføres derudover en erhvervsrettet lempelse af PSO for el på knap 1 mia. kr. årligt i 2015 og 2016 stigende til ca. 1,6 mia. kr. årligt fra 2017 og frem. Efter indregning af tilbageløb og adfærdsændringer skønnes lempelsen for erhverv at indebære et mindreprovenu på ca. 730 mio. kr. (2014-niveau) i 2020. \n\nEndvidere forhøjes stykafgiften på cigarillos, cerutter og cigarer m.v. til 50 øre pr. stk. i 2015, værdiafgiften på 10 pct. af detailprisen fastholdes, og der indføres en minimumsafgift på 130 øre pr. stk. inklusive moms i 2015. Herudover foretages en indeksering af styk- og minimumsafgiften med årligt 1,8 pct. i perioden 2015-2020. Efter indregning af tilbageløb og adfærdsændringer skønnes merprovenuet således at udgøre 40 mio. kr. årligt til og med 2020. \n\nLovforslaget indeholder elementer fra »Aftale om tilbagerulning af forsyningssikkerhedsafgiften m.v. og lempelser af PSO« og et element fra »Aftale om en vækstpakke«. Aftalerne er indgået mellem regeringen (Socialdemokratiet og Radikale Venstre), Venstre, Dansk Folkeparti, Socialistisk Folkeparti og Enhedslisten henholdsvis den 14. juli og den 2. juli 2014.","Forslag til lov om ændring af lov om afgift af elektricitet, lov om afgift af stenkul, brunkul og koks m.v., personskatteloven og forskellige andre love. (Tilbagerulning af forsyningssikkerhedsafgiften, nedsættelse af elvarmeafgiften, forhøjelse af elafgiften, tilpasning af afgiftsregler for VE-brændsler, forhøjelse af bundskatten og det skrå skatteloft, nedsættelse af den grønne check og afgiftsforhøjelse på cigarillos m.v.). Lovforslaget betyder, at afgiftsforhøjelserne på fossile brændsler og den nye afgift på VE-brændsler, der følger af forsyningssikkerhedsafgiften, afskaffes fra den 1. januar 2015. Derudover nedsættes energiafgifterne på fossile brændsler (olie, kul og gas) med 7,9 kr./GJ, og elvarmeafgiften nedsættes parallelt. Desuden justeres afgifterne vedrørende bioolier m.v. Samlet skønnes tilbagerulningen af forsyningssikkerhedsafgiften m.v. at indebære et mindreprovenu efter indregning af tilbageløb og adfærdsændringer på ca. 3,0 mia. kr. (2014-niveau) i 2020. Tilbagerulningen finansieres ved en forhøjelse af bundskattesatsen og det skrå skatteloft med 0,28 procentpoint og en reduktion af den grønne check med 425 kr. i 2020 (fra 1.300 kr. til 875 kr.), når tilbagerulningen er fuldt indfaset. \n\nDer gennemføres derudover en erhvervsrettet lempelse af PSO for el på knap 1 mia. kr. årligt i 2015 og 2016 stigende til ca. 1,6 mia. kr. årligt fra 2017 og frem. Efter indregning af tilbageløb og adfærdsændringer skønnes lempelsen for erhverv at indebære et mindreprovenu på ca. 730 mio. kr. (2014-niveau) i 2020. \n\nEndvidere forhøjes stykafgiften på cigarillos, cerutter og cigarer m.v. til 50 øre pr. stk. i 2015, værdiafgiften på 10 pct. af detailprisen fastholdes, og der indføres en minimumsafgift på 130 øre pr. stk. inklusive moms i 2015. Herudover foretages en indeksering af styk- og minimumsafgiften med årligt 1,8 pct. i perioden 2015-2020. Efter indregning af tilbageløb og adfærdsændringer skønnes merprovenuet således at udgøre 40 mio. kr. årligt til og med 2020. \n\nLovforslaget indeholder elementer fra »Aftale om tilbagerulning af forsyningssikkerhedsafgiften m.v. og lempelser af PSO« og et element fra »Aftale om en vækstpakke«. Aftalerne er indgået mellem regeringen (Socialdemokratiet og Radikale Venstre), Venstre, Dansk Folkeparti, Socialistisk Folkeparti og Enhedslisten henholdsvis den 14. juli og den 2. juli 2014."
2,L 33,Forslag til lov om ændring af lov om produktionsskoler. (Ophævelse af revisionsbestemmelse m.v.).,"Lovforslaget indebærer, at ordningen med, at alle produktionsskoledeltagere kan få et kompetencebevis, når de har afsluttet deres produktionsskoleforløb, bliver gjort permanent. Kompetencebeviset dokumenterer varighed og indhold af det konkrete forløb og dokumenterer de faglige kompetencer, som deltageren har opnået under produktionsskoleforløbet.","Forslag til lov om ændring af lov om produktionsskoler. (Ophævelse af revisionsbestemmelse m.v.). Lovforslaget indebærer, at ordningen med, at alle produktionsskoledeltagere kan få et kompetencebevis, når de har afsluttet deres produktionsskoleforløb, bliver gjort permanent. Kompetencebeviset dokumenterer varighed og indhold af det konkrete forløb og dokumenterer de faglige kompetencer, som deltageren har opnået under produktionsskoleforløbet."
3,L 19,Forslag til lov om dansk turisme.,"Lovforslaget etablerer et nationalt turismeforum, som skal koordinere og styre den offentlige turismefremmeindsats i Danmark. Det nationale turismeforum skal udarbejde en national strategi for dansk turisme med centrale prioriteter og mål for fremme af dansk turisme og igangsætte analyser, herunder en større årlig analyse af udviklingen i dansk turisme. Forummet skal endvidere årligt udarbejde en rapport til erhvervs- og vækstministeren om status for udmøntningen af den nationale strategi.\n\nI tilknytning til det nationale turismeforum etableres et rådgivende organ, Dansk Turismes Advisory Board, som består af organisationer og øvrige relevante ministerier. Advisoryboardet skal medvirke til, at der er sammenhæng mellem målene for den offentlige turismefremmeindsats og relevante sektorområder inden for turismen og erhvervets efterspørgsel og udviklingsmuligheder. \n\nUdviklingsindsatsen samles under tre regionale udviklingsselskaber for turisme, der får ansvaret for udviklingen af dansk turisme inden for de tre forretningsområder kyst- og naturturismen, erhvervs- og mødeturismen samt storbyturismen. Selskaberne skal udarbejde udviklingsstrategier for hvert forretningsområde og afrapportere til det nationale turismeforum. Status for udmøntningen af strategierne vil indgå i den årlige rapport til erhvervs- og vækstministeren. \n\nFormålet med lovforslaget er at skabe en stærkere organisering og styring af den offentlige turismefremmeindsats. Lovforslaget følger op på den politiske aftale om vækstplan for dansk turisme fra juni 2014 mellem regeringen (Socialdemokratiet og Radikale Venstre), Venstre, Dansk Folkeparti, Socialistisk Folkeparti, Enhedslisten og Det Konservative Folkeparti.\n\nLoven træder i kraft den 1. januar 2015.","Forslag til lov om dansk turisme. Lovforslaget etablerer et nationalt turismeforum, som skal koordinere og styre den offentlige turismefremmeindsats i Danmark. Det nationale turismeforum skal udarbejde en national strategi for dansk turisme med centrale prioriteter og mål for fremme af dansk turisme og igangsætte analyser, herunder en større årlig analyse af udviklingen i dansk turisme. Forummet skal endvidere årligt udarbejde en rapport til erhvervs- og vækstministeren om status for udmøntningen af den nationale strategi.\n\nI tilknytning til det nationale turismeforum etableres et rådgivende organ, Dansk Turismes Advisory Board, som består af organisationer og øvrige relevante ministerier. Advisoryboardet skal medvirke til, at der er sammenhæng mellem målene for den offentlige turismefremmeindsats og relevante sektorområder inden for turismen og erhvervets efterspørgsel og udviklingsmuligheder. \n\nUdviklingsindsatsen samles under tre regionale udviklingsselskaber for turisme, der får ansvaret for udviklingen af dansk turisme inden for de tre forretningsområder kyst- og naturturismen, erhvervs- og mødeturismen samt storbyturismen. Selskaberne skal udarbejde udviklingsstrategier for hvert forretningsområde og afrapportere til det nationale turismeforum. Status for udmøntningen af strategierne vil indgå i den årlige rapport til erhvervs- og vækstministeren. \n\nFormålet med lovforslaget er at skabe en stærkere organisering og styring af den offentlige turismefremmeindsats. Lovforslaget følger op på den politiske aftale om vækstplan for dansk turisme fra juni 2014 mellem regeringen (Socialdemokratiet og Radikale Venstre), Venstre, Dansk Folkeparti, Socialistisk Folkeparti, Enhedslisten og Det Konservative Folkeparti.\n\nLoven træder i kraft den 1. januar 2015."
4,L 13,Forslag til lov om ændring af lov om aktiv socialpolitik. (Ændring af formue- og fradragsregler ved efterbetaling af offentlige forsørgelsesydelser og øvrige offentlige sociale ydelser m.v.).,"Formålet med lovforslaget er at sikre, at personer, der får efterbetalt en social ydelse f.eks. som led i en sag vundet ved Ankestyrelsen om retten til sygedagpenge, ikke efterfølgende mister deres uddannelses- eller kontanthjælp på grund af formue- og fradragsreglerne i kontanthjælpslovgivningen. Personer, der ikke har fået udbetalt den korrekte ydelse, og som derfor kan have stiftet gæld, skal have mulighed for f.eks. at anvende efterbetalingen til at tilbagebetale gælden. Der skal derfor ses bort fra efterbetalingen i 2 år efter udbetalingen. De ændrede regler får også betydning for personer, der modtager ressourceforløbsydelse, idet reglerne om fradrag af indtægter i kontant- og uddannelseshjælp finder tilsvarende anvendelse, for så vidt angår egne indtægter.\n\nLovforslaget udmønter aftalen om ændring af formue- og fradragsreglerne i kontanthjælpslovgivningen ved efterbetaling af sociale ydelser, som regeringen (Socialdemokraterne og Radikale Venstre) indgik den 8. maj 2014 med Enhedslisten og Socialistisk Folkeparti.\n\n","Forslag til lov om ændring af lov om aktiv socialpolitik. (Ændring af formue- og fradragsregler ved efterbetaling af offentlige forsørgelsesydelser og øvrige offentlige sociale ydelser m.v.). Formålet med lovforslaget er at sikre, at personer, der får efterbetalt en social ydelse f.eks. som led i en sag vundet ved Ankestyrelsen om retten til sygedagpenge, ikke efterfølgende mister deres uddannelses- eller kontanthjælp på grund af formue- og fradragsreglerne i kontanthjælpslovgivningen. Personer, der ikke har fået udbetalt den korrekte ydelse, og som derfor kan have stiftet gæld, skal have mulighed for f.eks. at anvende efterbetalingen til at tilbagebetale gælden. Der skal derfor ses bort fra efterbetalingen i 2 år efter udbetalingen. De ændrede regler får også betydning for personer, der modtager ressourceforløbsydelse, idet reglerne om fradrag af indtægter i kontant- og uddannelseshjælp finder tilsvarende anvendelse, for så vidt angår egne indtægter.\n\nLovforslaget udmønter aftalen om ændring af formue- og fradragsreglerne i kontanthjælpslovgivningen ved efterbetaling af sociale ydelser, som regeringen (Socialdemokraterne og Radikale Venstre) indgik den 8. maj 2014 med Enhedslisten og Socialistisk Folkeparti.\n\n"
5,L 14,Forslag til lov om ændring af lov om ferie. (Færre betingelser for optjening af sygeferiegodtgørelse og fællesopkrævning fra arbejdsgivere for betalingen til Feriepengeinfo m.v.).,"Lovforslaget har til formål at sikre lønmodtagere, der ikke har ret til fuld løn under sygdom, ret til at optjene minimum 4 ugers betalt ferie om året eller en forholdsmæssig andel heraf. Dette sikres ved, at en lønmodtager, der ikke har ret til fuld løn under sygdom, som udgangspunkt har ret til sygeferiegodtgørelse fra 2. sygefraværsdag under hver periode med sygefravær i optjeningsåret.\n\nDesuden indeholder lovforslaget hjemmel til, at arbejdsgivernes betaling for Feriepengeinfo kan ske via en fælles opkrævning, der administreres af Arbejdsgivernes Tillægspension (ATP). Betalingen for Feriekontos administration af Feriepengeinfo kan opkræves via ATP's fællesopkrævning for de arbejdsgivere, der indberetter oplysninger om feriegodtgørelse til Feriepengeinfo via indkomstregisteret. Feriepengeinfo er en portal, der fra den 1. maj 2015 skal indeholde oplysninger om alle lønmodtageres optjente feriegodtgørelse. Lønmodtagerne får et samlet overblik over optjent ferie med feriegodtgørelse, og de skal anmode udbetaleren om feriegodtgørelsen via portalen.","Forslag til lov om ændring af lov om ferie. (Færre betingelser for optjening af sygeferiegodtgørelse og fællesopkrævning fra arbejdsgivere for betalingen til Feriepengeinfo m.v.). Lovforslaget har til formål at sikre lønmodtagere, der ikke har ret til fuld løn under sygdom, ret til at optjene minimum 4 ugers betalt ferie om året eller en forholdsmæssig andel heraf. Dette sikres ved, at en lønmodtager, der ikke har ret til fuld løn under sygdom, som udgangspunkt har ret til sygeferiegodtgørelse fra 2. sygefraværsdag under hver periode med sygefravær i optjeningsåret.\n\nDesuden indeholder lovforslaget hjemmel til, at arbejdsgivernes betaling for Feriepengeinfo kan ske via en fælles opkrævning, der administreres af Arbejdsgivernes Tillægspension (ATP). Betalingen for Feriekontos administration af Feriepengeinfo kan opkræves via ATP's fællesopkrævning for de arbejdsgivere, der indberetter oplysninger om feriegodtgørelse til Feriepengeinfo via indkomstregisteret. Feriepengeinfo er en portal, der fra den 1. maj 2015 skal indeholde oplysninger om alle lønmodtageres optjente feriegodtgørelse. Lønmodtagerne får et samlet overblik over optjent ferie med feriegodtgørelse, og de skal anmode udbetaleren om feriegodtgørelsen via portalen."

# We now have to df's: Questions and Cases. 

I will try a simple embedding model and try a single question against all 2,128 cases.

In [2]:
from sentence_transformers import SentenceTransformer

model = SentenceTransformer(
    "intfloat/multilingual-e5-base"
)

ModuleNotFoundError: No module named 'sentence_transformers'